apiVersion: v2
name: rclone-server
description: A Helm chart for RClone File Browser Server with POSIX mount support
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - rclone
  - storage
  - minio
  - s3
  - file-browser
  - posix
  - fuse
maintainers:
  - name: khoa-nguyendang
    email: your-email@example.com
home: https://github.com/khoa-nguyendang/rclone-file-upload
sources:
  - https://github.com/khoa-nguyendang/rclone-file-upload